/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IAirnodeRrpV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAirnodeRrpV0__factory>;
    getContractFactory(
      name: "IAuthorizationUtilsV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuthorizationUtilsV0__factory>;
    getContractFactory(
      name: "ITemplateUtilsV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITemplateUtilsV0__factory>;
    getContractFactory(
      name: "IWithdrawalUtilsV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWithdrawalUtilsV0__factory>;
    getContractFactory(
      name: "RrpRequesterV0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RrpRequesterV0__factory>;
    getContractFactory(
      name: "Demo",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Demo__factory>;

    getContractAt(
      name: "IAirnodeRrpV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAirnodeRrpV0>;
    getContractAt(
      name: "IAuthorizationUtilsV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuthorizationUtilsV0>;
    getContractAt(
      name: "ITemplateUtilsV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITemplateUtilsV0>;
    getContractAt(
      name: "IWithdrawalUtilsV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWithdrawalUtilsV0>;
    getContractAt(
      name: "RrpRequesterV0",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RrpRequesterV0>;
    getContractAt(
      name: "Demo",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Demo>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
